version: '3'

services:
  db:
    build: './sql'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      rephrasing_net:
        ipv4_address: '${DB_HOST}'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '512M'
  api:
    build: './server'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      rephrasing_net:
        ipv4_address: '${SERVER_HOSTNAME}'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '256M'
  web:
    build: './client'
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    env_file:
      - .env
    environment:
      - 'REACT_APP_SERVER_HOSTNAME=${SERVER_HOSTNAME}'
      - 'REACT_APP_SERVER_PORT=${SERVER_PORT}'
      - 'REACT_APP_HTTPS=${HTTPS}'
    depends_on:
      - api
    networks:
      rephrasing_net:
        ipv4_address: '${CLIENT_HOSTNAME}'
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '256M'
volumes:
  db_data:
networks:
  rephrasing_net:
    driver: bridge
    ipam:
      config:
        - subnet: '${NETWORK_IP}'
          gateway: '${GATEWAY_IP}'
